version: '3.8'
services:
  nodejs-server:
    build:
      context: .
    container_name: node-api
    env_file: .env
    environment:
      - PORT=$PORT
      - ENV=$ENV
      - MONGO_URI=$MONGO_URI
      - AGENDA_DB_COLLECTION=$AGENDA_DB_COLLECTION
      - AGENDA_POOL_TIME=$AGENDA_POOL_TIME
      - AGENDA_CONCURRENCY=$AGENDA_CONCURRENCY
      - WINSTON_LOG_LEVEL=$WINSTON_LOG_LEVEL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - EMAIL_FROM=$EMAIL_FROM
      - EMAIL_REPLY_TO=$EMAIL_REPLY_TO
      - EMAIL_ADMIN_EMAIL_ADDRESS=$EMAIL_ADMIN_EMAIL_ADDRESS
      - JWT_SECRET_ACCESS_TOKEN=$JWT_SECRET_ACCESS_TOKEN
      - JWT_ACCESS_TOKEN_EXPIRY_IN_MINUTES=$JWT_ACCESS_TOKEN_EXPIRY_IN_MINUTES
      - JWT_SECRET_REFRESH_TOKEN=$JWT_SECRET_REFRESH_TOKEN
      - JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES=$JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES
    ports:
      - $PORT:$PORT
    # links:
    #   - db
  # db:
  #   image: mongo:3
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$DB_USER
  #     - MONGO_INITDB_ROOT_PASSWORD=$DB_PASSWORD
  #     - MONGO_INITDB_DATABASE=$DB_NAME
