version: '3.8'
services:
  nodejs-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: development-node-api
    env_file: .env
    environment:
      - PORT=$PORT
      - ENV=$ENV
      - MONGO_URI=$MONGO_URI
      - AGENDA_DB_COLLECTION=$AGENDA_DB_COLLECTION
      - AGENDA_POOL_TIME=$AGENDA_POOL_TIME
      - AGENDA_CONCURRENCY=$AGENDA_CONCURRENCY
      - WINSTON_LOG_LEVEL=$WINSTON_LOG_LEVEL
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - EMAIL_FROM=$EMAIL_FROM
      - EMAIL_REPLY_TO=$EMAIL_REPLY_TO
      - EMAIL_ADMIN_EMAIL_ADDRESS=$EMAIL_ADMIN_EMAIL_ADDRESS
      - JWT_SECRET_ACCESS_TOKEN=$JWT_SECRET_ACCESS_TOKEN
      - JWT_ACCESS_TOKEN_EXPIRY_IN_MINUTES=$JWT_ACCESS_TOKEN_EXPIRY_IN_MINUTES
      - JWT_SECRET_REFRESH_TOKEN=$JWT_SECRET_REFRESH_TOKEN
      - JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES=$JWT_REFRESH_TOKEN_EXPIRY_IN_MINUTES
    ports:
      - $PORT:$PORT
    depends_on:
      - db
    init: true

    volumes:
      - ../:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"


  db:
    image: mongo:4.4.6
    restart: always
    container_name: db
    ports:
      - 27020:27017
    volumes:
      - db:/data/db

volumes:
  db:
